name: Deploy Document Processing Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Or your preferred region

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: Build SAM application
        run: sam build

      - name: Deploy SAM application
        # --- THIS IS THE CORRECTED LINE ---
        run: sam deploy --no-confirm-changeset